In [1]:
import os
import pandas as pd
import plotly.express as px
from datetime import datetime

In [ ]:
path_sampled_music = "music_sample.csv"
path_sampled_participants = "participant_sample.csv"
path_sampled_responses = "survey_sample.csv"


df_participants = pd.read_csv(path_sampled_participants).fillna(False)
df_participants["created_at"] = pd.to_datetime(df_participants["created_at"])
# df_participants.loc[df_participants["id"]=="P02", "is_withdrawn"]=True # Simulate particpant withdrew
df_participants = df_participants[df_participants["is_withdrawn"]==False].reset_index(drop=True).copy()

df_music = pd.read_csv(path_sampled_music)
df_music = (pd.merge(df_music, df_participants.rename({"id":"participant_id", "pid":"participant_pid"}, axis=1),
                        on="participant_pid", how="inner"))



df_responses = pd.read_csv(path_sampled_responses)
df_responses["participant_id"] = df_responses["participant_id"].apply(lambda x: f"P{str(x).zfill(2)}")
df_responses = (pd.merge(df_responses, df_participants.rename({"id":"participant_id", "pid":"participant_pid"}, axis=1),
                        on="participant_id", how="inner"))

df_responses

,participant_id,questionnaire,item,response,participant_pid,created_at,is_withdrawn
0,P01,tipi,1,3,BGS16,2024-12-12 07:48:42,False
1,P01,tipi,2,5,BGS16,2024-12-12 07:48:42,False
2,P01,tipi,3,1,BGS16,2024-12-12 07:48:42,False
3,P01,tipi,4,2,BGS16,2024-12-12 07:48:42,False
4,P01,tipi,5,4,BGS16,2024-12-12 07:48:42,False
...,...,...,...,...,...,...,...
271,P03,gms,35,0.5,TGUOG,2024-12-12 15:44:50,False
272,P03,gms,36,1,TGUOG,2024-12-12 15:44:50,False
273,P03,gms,37,1,TGUOG,2024-12-12 15:44:50,False
274,P03,gms,38,30-60 min,TGUOG,2024-12-12 15:44:50,False
275,P03,gms,39,Trumpet,TGUOG,2024-12-12 15:44:50,False

In [3]:
for quest in df_responses["questionnaire"].unique():
    df_questionnaire = df_responses[df_responses["questionnaire"]==quest][["participant_id", "item", "response"]].copy()
    df_questionnaire = df_questionnaire.set_index(['item', 'participant_id']).unstack(['item']).droplevel(level=0,axis=1)
    df_questionnaire.columns = [f"item_{c}"for c in df_questionnaire.columns]
    # df_questionnaire.to_csv(os.path.join("../data/raw/psychometrics",f"{quest}.csv"))

In [4]:
df_questionnaire = df_responses[df_responses["questionnaire"]=="tipi"][["participant_id", "item", "response"]].copy()

df_questionnaire = df_questionnaire.set_index(['item', 'participant_id']).unstack(['item']).droplevel(level=0,axis=1)
df_questionnaire.columns = [f"item_{c}"for c in df_questionnaire.columns]
df_questionnaire

,item_1,item_2,item_3,item_4,item_5,item_6,item_7,item_8,item_9,item_10
participant_id,,,,,,,,,,
P01,3,5,1,2,4,3,5,6,5,5
P02,5,5,7,2,7,5,6,6,6,7
P03,3,4,3,5,3,4,4,4,4,4

In [5]:
survey_data_example = {'survey_demo_data': {'demo_1': 'male', 'demo_10': 'student', 'demo_11': '', 'demo_12': 'Computer Science',
                                            'demo_13': 'home', 'demo_14': 'very-satisfied', 'demo_15': 'no', 'demo_16': '',
                                            'demo_17': 'frequent-changes&direction-planning', 'demo_18': 'sedentary', 'demo_19': 'take-instructions',
                                            'demo_2': '', 'demo_20': 'advanced', 'demo_21': 'left', 'demo_22': 'affect-regulation&sleep-aid&other',
                                            'demo_23': 'Relaxation', 'demo_24': 'very-likely', 'demo_25': 'apple-music', 'demo_26': '', 
                                            'demo_3': '25-34', 'demo_4': 'hispanic', 'demo_5': '', 'demo_6': 'master', 'demo_7': '', 'demo_8': 'spanish',
                                            'demo_9': ''}, 
                        'survey_tipi_data': {'tipi_1': '7', 'tipi_10': '3', 'tipi_2': '3', 'tipi_3': '2', 'tipi_4': '3', 'tipi_5': '3', 'tipi_6': '2', 
                                             'tipi_7': '3', 'tipi_8': '2', 'tipi_9': '3'}, 
                        'survey_panas_data': {'panas_1': '2', 'panas_10': '3', 'panas_11': '3', 'panas_12': '3', 'panas_13': '2', 'panas_14': '3', 
                                              'panas_15': '3', 'panas_16': '2', 'panas_17': '3', 'panas_18': '3', 'panas_19': '3', 'panas_2': '2', 
                                              'panas_20': '3', 'panas_3': '3', 'panas_4': '3', 'panas_5': '3', 'panas_6': '2', 'panas_7': '3', 
                                              'panas_8': '3', 'panas_9': '2'}, 
                        'survey_pss_data': {'pss_1': '1', 'pss_10': '3', 'pss_11': '2', 'pss_12': '3', 'pss_13': '3', 'pss_14': '2', 'pss_2': '3',
                                             'pss_3': '3', 'pss_4': '2', 'pss_5': '3', 'pss_6': '3', 'pss_7': '2', 'pss_8': '3', 'pss_9': '2'},
                        'survey_phq9_data': {'phq9_1': '1', 'phq9_2': '3', 'phq9_3': '3', 'phq9_4': '3', 'phq9_5': '2', 'phq9_6': '3', 'phq9_7': '2',
                                            'phq9_8': '3', 'phq9_9': '3'}, 
                        'survey_stompr_data': {'stompr_1': '1', 'stompr_10': '3', 'stompr_11': '2', 'stompr_12': '3', 'stompr_13': '3', 'stompr_14': '3',
                                               'stompr_15': '2', 'stompr_16': '3', 'stompr_17': '3', 'stompr_18': '2', 'stompr_19': '3', 'stompr_2': '2',
                                               'stompr_20': '3', 'stompr_21': '2', 'stompr_22': '3', 'stompr_23': '3', 'stompr_3': '2', 'stompr_4': '3',
                                               'stompr_5': '3', 'stompr_6': '2', 'stompr_7': '3', 'stompr_8': '2', 'stompr_9': '3'},
                        'survey_gms_data': {'gms_1': '1', 'gms_2': '2', 'gms_3': '3', 'gms_4': '3', 'gms_5': '3', 'gms_6': '3', 'gms_7': '3', 'gms_8': '3',
                                            'gms_9': '2', 'gms_10': '3', 'gms_11': '2', 'gms_12': '3', 'gms_13': '3', 'gms_14': '2', 'gms_15': '3',
                                            'gms_16': '3', 'gms_17': '2', 'gms_18': '3', 'gms_19': '3', 'gms_20': '3', 'gms_21': '2', 'gms_22': '2',
                                            'gms_23': '3', 'gms_24': '3', 'gms_25': '7', 'gms_26': '3', 'gms_27': '2', 'gms_28': '3', 'gms_29': '1',
                                            'gms_30': '1', 'gms_31': '1', 'gms_32': '4-5', 'gms_33': '0.5', 'gms_34': '3', 'gms_35': '2', 'gms_36': '2',
                                            'gms_37': '3', 'gms_38': '15-30 min', 'gms_39': 'Guitar'}}

dummy_id = 4
survey_survey_record = {}
for key_survey, value_response in survey_data_example.items():
    str_item = list(value_response.keys())
    for item_question in str_item:
        value_response[int(item_question.split("_")[1])] = value_response.pop(item_question)
    survey_record = pd.DataFrame.from_records([value_response])
    survey_record = survey_record[sorted(survey_record.columns)]
    survey_record.rename(columns=lambda col: f"item_{col}", inplace=True)
    survey_record.rename(index={0: f"P{str(dummy_id).zfill(2)}"}, inplace=True)
    survey_record.index.name = "participant_id"
    survey_survey_record[key_survey] = survey_record

In [6]:
survey_survey_record["survey_tipi_data"]

,item_1,item_2,item_3,item_4,item_5,item_6,item_7,item_8,item_9,item_10
participant_id,,,,,,,,,,
P04,7,3,2,3,3,2,3,2,3,3

In [7]:
pd.concat([df_questionnaire, survey_survey_record["survey_tipi_data"]])

,item_1,item_2,item_3,item_4,item_5,item_6,item_7,item_8,item_9,item_10
participant_id,,,,,,,,,,
P01,3,5,1,2,4,3,5,6,5,5
P02,5,5,7,2,7,5,6,6,6,7
P03,3,4,3,5,3,4,4,4,4,4
P04,7,3,2,3,3,2,3,2,3,3

In [8]:
# TIPI scoring function
def score_tipi(df_grouped):
    """
    Compute TIPI scores for participant. 
    Five Personality Traits:

    Extraversion (EXT): 1 and 6R
    Agreeableness (AGR): 2R and 7
    Conscientiousness (CON): 3 and 8R
    Emotional Stability (ES): 4R and 9
    Openness (OPN): 5 and 10R

    Reverse score: recode a 7 with a 1, a 6 with a 2, a 5 with a 3, etc.)
    """

    # Define scoring logic
    tipi_scores = {
        ("TIPI", "EXT"): lambda df: (df.loc[df["item"] == 1, "response"].values[0] +
                           (8 - df.loc[df["item"] == 6, "response"].values[0])) / 2,
        ("TIPI", "AGR"): lambda df: (df.loc[df["item"] == 7, "response"].values[0] +
                           (8 - df.loc[df["item"] == 2, "response"].values[0])) / 2,
        ("TIPI", "CON"): lambda df: (df.loc[df["item"] == 3, "response"].values[0] +
                           (8 - df.loc[df["item"] == 8, "response"].values[0])) / 2,
        ("TIPI","ES"): lambda df: (df.loc[df["item"] == 9, "response"].values[0] +
                           (8 - df.loc[df["item"] == 4, "response"].values[0])) / 2,
        ("TIPI","OPN"): lambda df: (df.loc[df["item"] == 5, "response"].values[0] +
                           (8 - df.loc[df["item"] == 10, "response"].values[0])) / 2,
    }

    # Make sure responses are int
    df_grouped["response"] = df_grouped["response"].astype(int)

    # Calculate scores
    scores = {dimension: score_func(df_grouped) for dimension, score_func in tipi_scores.items()}
    return scores


def score_panas(df_grouped):
    """
    Compute PANAS scores.
    Postive Affect Score (PAS): 1, 3, 5, 9, 10, 12, 14, 16, 17, 19
    Negative Affect Score (NAS): 2, 4, 6, 7, 8, 11, 13, 15, 18, 20

    """

    panas_scores = {
        ("PANAS","PAS"): lambda df: df.loc[df["item"].isin([1, 3, 5, 9, 10, 12, 14, 16, 17, 19])]["response"].sum(),
        ("PANAS", "NAS"): lambda df: df.loc[df["item"].isin([2, 4, 6, 7, 8, 11, 13, 15, 18, 20])]["response"].sum()
    }

    # Make sure responses are int
    df_grouped["response"] = df_grouped["response"].astype(int)

    #Calculate scores
    scores = {dimension: score_func(df_grouped) for dimension, score_func in panas_scores.items()}

    return scores


def score_stompr(df_grouped):
    """
    Compute STOMP-R scores.
    Four broad music-preference dimensions:

    Reflective & Complex (RC): 2, 3, 4, 7, 11, 12, 13, 15
    Intense & Rebellious (IR): 1, 10, 17, 21
    Upbeat & Conventional (UC): 5, 9, 14, 16, 20, 23
    Energetic & Rhythmic (ER): 6, 8, 18, 19, 22

    """

    stompr_scores = {
        ("STOMPR","RC"): lambda df: df.loc[df["item"].isin([2, 3, 4, 7, 11, 12, 13, 15])]["response"].mean().round(2),
        ("STOMPR", "IR"): lambda df: df.loc[df["item"].isin([1, 10, 17, 21])]["response"].mean().round(2),
        ("STOMPR", "UC"): lambda df: df.loc[df["item"].isin([5, 9, 14, 16, 20, 23])]["response"].mean().round(2),
        ("STOMPR", "ER"): lambda df: df.loc[df["item"].isin([6, 8, 18, 19, 22])]["response"].mean().round(2)
    }

    # Make sure responses are int
    df_grouped["response"] = df_grouped["response"].astype(int)

    #Calculate scores
    scores = {dimension: score_func(df_grouped) for dimension, score_func in stompr_scores.items()}

    return scores


def score_gms(df_grouped):
    """
    Compute Goldsmiths scores.
    Five independent dimensions and one overal score:

    Active Engagement (AE): 1, 3, 8, 15, 21, 24, 28, 34, 38
    Perceptual Abilities (PA): 5, 6, 11, 12, 13, 18, 22, 23, 26
    Musical Training (MT): 14, 27, 32, 33, 35, 36, 37
    Singing Abilities (SA): 4, 7, 10, 17, 25, 29, 30
    Emotions (EMO): 2, 9, 16, 19, 20, 31

    General Sophistication (GS): 1, 3, 4, 7, 10, 12, 14, 15, 17, 19, 23, 24, 25, 27, 29, 32, 33, 37

    Categorial Items: 32, 33, 34, 35, 36 37, 38 
    Reverse-scored items: 9, 11, 13, 14, 17, 21, 23, 25, 27
    """

    gsm_cat = {32: ["0", "1", "2", "3", "4-5", "6-9", "10 or more"],
               33: ["0", "0.5", "1", "1.5", "2", "3-4", "5 or more"],
               34: ["0", "1", "2", "3", "4-6", "7-10", "11 or more"],
               35: ["0", "0.5", "1", "2", "3", "4-6", "7 or more"],
               36: ["0", "0.5", "1", "2", "3-5", "6-9", "10 or more"],
               37: ["0", "1", "2", "3", "4", "5", "6 or more"],
               38: ["0-15 min", "15-30 min", "30-60 min", "60-90 min", "2 hrs", "2-3 hrs", "4 hrs or more"]} 

    gms_scores = {
        ("GMS","AE"): lambda df_num, df_cat: (df_num[df_num["item"].isin([1, 3, 8, 15, 24, 28])]["response"].sum() +
                                     (8 - df_num[df_num["item"].isin([21])]["response"]).sum() +
                                      sum([gsm_cat[item_cat].index(df_cat.loc[df_cat["item"].isin([item_cat])]["response"].values[0]) + 1 
                                           for item_cat in [34,38] ])),
                                           
        ("GMS", "PA"): lambda df_num, _: (df_num.loc[df_num["item"].isin([5, 6, 12, 18, 22, 26])]["response"].sum() +
                                      (8- df_num.loc[df_num["item"].isin([11, 13, 23])]["response"]).sum() ),

        ("GMS", "MT"): lambda df_num, df_cat: ((8 - df_num[df_num["item"].isin([14, 27])]["response"]).sum() +
                                      sum([gsm_cat[item_cat].index(df_cat.loc[df_cat["item"].isin([item_cat])]["response"].values[0]) + 1 
                                           for item_cat in [32, 33, 35, 36, 37] ])),


        ("GMS", "SA"): lambda df_num, _: (df_num.loc[df_num["item"].isin([4, 7, 10, 29, 30])]["response"].sum() +
                                      (8- df_num.loc[df_num["item"].isin([17, 25])]["response"]).sum() ),

        ("GMS", "EMO"): lambda df_num, _: (df_num.loc[df_num["item"].isin([2, 16, 19, 20, 31])]["response"].sum() +
                                      (8- df_num.loc[df_num["item"].isin([9])]["response"]).sum() ),

        ("GMS", "GS"): lambda df_num, df_cat: (df_num[df_num["item"].isin([1, 3, 4, 7, 10, 12, 15, 19, 24, 29])]["response"].sum() +
                                     (8 - df_num[df_num["item"].isin([14, 17, 23, 25, 27])]["response"]).sum() +
                                      sum([gsm_cat[item_cat].index(df_cat.loc[df_cat["item"].isin([item_cat])]["response"].values[0]) + 1 
                                           for item_cat in [32,33,37] ])),
    }

    # Separate categorical and numerical items in different dataframes
    df_grouped_num = df_grouped.sort_values(by="item").iloc[:-8].copy()
    df_grouped_num["response"] = df_grouped_num["response"].astype(int)
    df_grouped_cat = df_grouped.sort_values(by="item").iloc[-8:-1].copy()

    #Calculate scores
    scores = {dimension: score_func(df_grouped_num, df_grouped_cat) for dimension, score_func in gms_scores.items()}

    return scores


def get_scores_psychometrics(df_answers):
    """

    """

    questionnaire_scoring = {"tipi":score_tipi, "panas":score_panas,
                             "stompr":score_stompr, "gms": score_gms}

    grouped = df_answers.groupby("participant_id")

    # Iterate questionnares scoring functions and 
    # participants
    scores_all = []
    for name, group in grouped:
        scores_participant = {"ID": name}
        for survey, func_score in questionnaire_scoring.items():
            # Get respones for items of current questionnaire and participant
            group_survey = group[group["questionnaire"]==survey].copy()
            survey_scores = func_score(group_survey)
            scores_participant = {**scores_participant, **survey_scores}
        # Include all in same list    
        scores_all.append(scores_participant)

    df_scores_all = pd.DataFrame(scores_all)
    df_scores_all.set_index("ID", inplace=True)
    df_scores_all.columns = pd.MultiIndex.from_tuples(df_scores_all.columns, names=["QUEST", "DIM"])

    return df_scores_all

df_scores = get_scores_psychometrics(df_responses).reset_index()
df_scores

QUEST   ID TIPI                     PANAS     STOMPR                  GMS      \
DIM         EXT  AGR  CON   ES  OPN   PAS NAS     RC    IR    UC   ER  AE  PA
0      P01  4.0  4.0  1.5  5.5  3.5    22  22   2.75  2.00  2.67  3.0  29  24
1      P02  4.0  4.5  4.5  6.0  4.0    21  29   2.75  3.25  2.33  2.6  29  31
2      P03  3.5  4.0  3.5  3.5  3.5    28  29   2.88  2.75  3.00  3.0  30  32

QUEST
DIM    MT  SA EMO  GS
0      29  20  11  64
1      27  24  16  65
2      22  22  18  59

In [9]:
# Convert data to Dash-friendly format
scores_columns = [{"name": list(col), "id": "".join(col)} for col in df_scores.columns]
df_scores.columns = [''.join(col) for col in df_scores.columns]
scores_records = df_scores.to_dict("records")

In [10]:
def top_tracks_listened(df_music_hist):

    df_top = (
        df_music_hist.groupby(['track_name','context', 'track_uri'])  # Include song_name in grouping
        .agg(
            listens=('track_uri', 'size'),
            unique_participants=('participant_id', pd.Series.nunique)
        )
        .reset_index()
        .sort_values(['context', 'listens'], ascending=[True, False])  # Sort by context and listens
        .groupby('context')  # Group by context again to get the top 3 tracks
        .head(3)
        .drop(columns=['track_uri'])
    )
    

    return df_top

df_top = top_tracks_listened(df_music)
df_top

,track_name,context,listens,unique_participants
313,Turn,Affective,3,2
19,Almost April,Affective,2,1
21,Amabile,Affective,2,1
332,When It Was Just A Dream,Eudaimonic,3,2
17,Alignment,Eudaimonic,2,2
40,Begynnelse (Ambient),Eudaimonic,2,2
97,Falke,Goal-Attainment,6,2
57,Charcoaled Walls,Goal-Attainment,5,2
265,Skyward,Goal-Attainment,5,2
0,13 Hz Concentration - Binaural Beats,Other,155,1
3,18 Hz Cognitive Thinking - Binaural Beats,Other,152,1
5,30 Hz Beta Waves - Binaural Beats,Other,151,1

In [11]:
# Convert data to Dash-friendly format
top_records = df_top.to_dict("records")
top_columns = [{"name": col, "id": col} for col in df_top.columns]

In [14]:
def create_bar_chart(df):

    counts_df = (df.groupby("participant_id", as_index=False)["context"]
                 .value_counts()
                 .sort_values(by="participant_id"))
    
    barplot = px.bar(
        counts_df,
        x="participant_id",
        y="count",
        color="context",
        text_auto=True,
        color_discrete_map={"Affective":"coral",
                        "Eudaimonic":"royalblue",
                        "Goal-Attainment":"lightgreen",
                        "Other":"mediumpurple"}
    )

    barplot.update_layout(
        xaxis_title='Participant ID',
        yaxis_title='Counts',
        title='Number of Songs Listened by Participants',
        template="plotly_white",
    )

    return barplot


# create_bar_chart(df_music)

In [13]:
progress_tracking = {"Participation Time":pd.Timedelta(days=21), "Affective":170, "Eudaimonic":149,"Goal-Attainment":167}

default_table = pd.DataFrame(0, index=list(df_participants['id']), columns=list(progress_tracking.keys()))

table = (df_music.groupby(["participant_id", "context"])["track_uri"]
                .apply(lambda x: len(x.unique()))
                .reset_index(name="counts")
                .pivot_table(index="participant_id", columns="context", values="counts")
                .fillna(0)
                .drop("Other",axis=1))

table = pd.concat([table, default_table[~default_table.index.isin(table.index)].dropna()]).astype(float)
table["Participation Time"] = ((datetime.today() - df_participants.set_index("id")["created_at"])).clip(upper=pd.Timedelta(days=21))

table = (table.div(pd.Series(progress_tracking)).applymap(lambda x: f"{x*100:,.2f}%")
         .reset_index()
         .rename(columns={'index': 'PID'}))
    
percentage_values = set(
    float(cell.strip('%')) for col in table.columns[1:] for cell in table[col] if isinstance(cell, str)
)

table

   PID Affective Eudaimonic Goal-Attainment Participation Time
0  P01    27.06%     13.42%          85.03%            100.00%
1  P02     0.00%      0.00%          41.32%            100.00%
2  P03     1.76%     16.78%           0.00%            100.00%
3  P04     0.00%      0.00%           0.00%             56.55%